export BUILD_TARGET := if os_family() == "windows" { "pc-windows-msvc" } else { "unknown-linux-gcc" } 

run:
    npm run run

build:
    #!/bin/bash
    export BUILD_DIR="../build/{{arch()}}-$BUILD_TARGET/release/install/sacro"
    npm run build
