---
name: CI

on:
  push:

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: "opensafely-core/setup-action@v1"
        with:
          python-version: "3.10"
          install-just: true
      - name: Check formatting, linting and import sorting
        run: just check

  test-linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: "opensafely-core/setup-action@v1"
        with:
          python-version: "3.10"
          install-just: true
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Run tests
        run: just test
      - name: Build binary
        run: just build
      - name: Build app
        run: just sacro-app/build

  build-windows:
    permissions:
      contents: write
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
      - uses: "opensafely-core/setup-action@v1"
        with:
          python-version: "3.11"
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      # our just setup doesn't make just available on the path
      - uses: extractions/setup-just@69d82fb0233557aec017ef13706851d0694e0f1d
      - name: Run tests
        run: just test
      - name: Build binary
        run: just build
      - name: Build app
        run: just sacro-app/build
        # this gets us cleaner paths in our artifact
      - name: Copy built msi
        run: cp sacro-app/dist/SACRO*.msi .
      - name: Upload build
        if: success() && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: SACRO-latest-windows-build
          path: |
            SACRO*.msi
            outputs/*
            !outputs/.keep

  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf  # v3.1.0
        with:
          failure-threshold: error
